(ns stratum.cached-storage
  "PSS-backed lazy storage for PersistentColumnIndex.

   Implements persistent-sorted-set's IStorage protocol with:
   - Konserve backend for durable persistence
   - LRU cache for frequently accessed nodes
   - Content-addressed (merkle) or random UUID addressing
   - Fressian serialization for PSS nodes and stratum domain types

   Following the datahike/proximum CachedStorage pattern."
  (:require [clojure.core.async :as async]
            [clojure.core.cache :as cache]
            [konserve.core :as k]
            [konserve.serializers :refer [fressian-serializer]]
            [hasch.core :as hasch]
            [stratum.chunk :as chunk]
            [stratum.stats :as stats])
  (:import [org.fressian.handlers WriteHandler ReadHandler]
           [org.replikativ.persistent_sorted_set
            IStorage Leaf Branch ANode Settings
            PersistentSortedSet RefType IMeasure]
           [stratum.chunk PersistentColChunk]
           [stratum.stats ChunkStats]
           [java.util List UUID]))

(set! *warn-on-reflection* true)

;; ============================================================================
;; Configuration
;; ============================================================================

(def ^:const BRANCHING_FACTOR
  "PSS branching factor. BF=64 gives ~4MB leaves (64 chunks x 64KB each),
   good granularity for partial loading at billion-row scale."
  64)

;; ============================================================================
;; ChunkEntry import (avoid circular dep by using the record directly)
;; ============================================================================

;; ChunkEntry is a defrecord from stratum.index with fields:
;;   chunk-id, chunk, stats
;; Use delay+resolve to get the actual class from Clojure's classloader
;; (Class/forName uses the system classloader which may differ).
(def ^:private chunk-entry-class
  (delay (let [ctor (resolve 'stratum.index/->ChunkEntry)]
           (class (ctor nil nil nil)))))

(defn- chunk-entry?
  "Check if x is a ChunkEntry record."
  [x]
  (instance? @chunk-entry-class x))

(defn- make-chunk-entry
  "Create a ChunkEntry record from components."
  [chunk-id chunk stats]
  ;; Use the positional factory fn generated by defrecord
  (let [ctor (resolve 'stratum.index/->ChunkEntry)]
    (ctor chunk-id chunk stats)))

;; ============================================================================
;; Measure Ops (needed for Settings in deserialized PSS nodes)
;; ============================================================================

(defn- create-measure-ops
  "Create ChunkEntryMeasureOps instance for PSS Settings.
   Lazy to avoid circular dependency with stratum.index."
  ^IMeasure []
  (let [ctor (resolve 'stratum.index/->ChunkEntryMeasureOps)]
    (ctor)))

;; ============================================================================
;; Address Generation
;; ============================================================================

(defn- hashable-leaf-keys
  "Extract hashable representations from leaf keys (ChunkEntries).
   hasch can't hash PersistentColChunk directly, so we extract chunk-id + stats."
  [keys]
  (mapv (fn [entry]
          (if (chunk-entry? entry)
            [(:chunk-id entry)
             (let [s (:stats entry)]
               {:count (:count s) :sum (:sum s) :min-val (:min-val s) :max-val (:max-val s)})]
            entry))
        keys))

(defn gen-address
  "Generate UUID address for B-tree nodes.

   When crypto-hash? is true, computes content-based address (merkle tree):
   - Branch: hash of child addresses
   - Leaf: hash of chunk-ids + stats (not raw chunk data — hasch can't serialize ColChunks)
   When false, generates random UUID."
  [^ANode node crypto-hash?]
  (if crypto-hash?
    (if (instance? Branch node)
      (hasch/uuid (vec (.addresses ^Branch node)))
      (hasch/uuid (hashable-leaf-keys (.keys ^Leaf node))))
    (UUID/randomUUID)))

;; ============================================================================
;; CachedStorage Implementation
;; ============================================================================

(defrecord CachedStorage [store config cache stats pending-writes]
  IStorage
  (store [_this node]
    (swap! stats update :writes inc)
    (let [address (gen-address node (:crypto-hash? config))]
      (swap! pending-writes conj [address node])
      (swap! cache cache/miss address node)
      address))

  (accessed [_this address]
    (swap! stats update :accessed inc)
    (swap! cache cache/hit address)
    nil)

  (restore [_this address]
    (if-let [cached (cache/lookup @cache address)]
      (do
        (swap! cache cache/hit address)
        cached)
      (let [node (k/get store address nil {:sync? true})]
        (when (nil? node)
          (throw (ex-info "PSS node not found in storage"
                          {:address address
                           :crypto-hash? (:crypto-hash? config)})))
        (swap! stats update :reads inc)
        (swap! cache cache/miss address node)
        node))))

;; ============================================================================
;; Fressian Handlers
;; ============================================================================

(defn create-fressian-handlers
  "Create Fressian read/write handlers for PSS nodes and stratum domain types.

   The storage-atom resolves the circular reference: deserialized PersistentSortedSet
   nodes need their IStorage to lazy-load children, but the storage holds the store
   which holds the serializer which holds the handlers."
  [storage-atom]
  (let [measure-ops (create-measure-ops)
        settings (Settings. (int BRANCHING_FACTOR) RefType/WEAK measure-ops)]
    {:read-handlers
     {;; PSS top-level set
      "stratum.PersistentSortedSet"
      (reify ReadHandler
        (read [_ reader _tag _component-count]
          (let [{:keys [meta address count]} (.readObject reader)]
            (PersistentSortedSet. meta nil address @storage-atom nil (int count) settings 0))))

      ;; PSS Leaf node
      "stratum.PersistentSortedSet.Leaf"
      (reify ReadHandler
        (read [_ reader _tag _component-count]
          (let [{:keys [keys]} (.readObject reader)]
            (Leaf. ^List keys settings))))

      ;; PSS Branch node
      "stratum.PersistentSortedSet.Branch"
      (reify ReadHandler
        (read [_ reader _tag _component-count]
          (let [{:keys [keys level addresses]} (.readObject reader)]
            (Branch. (int level) ^List keys ^List (seq addresses) settings))))

      ;; ChunkEntry (defrecord from stratum.index)
      "stratum.ChunkEntry"
      (reify ReadHandler
        (read [_ reader _tag _component-count]
          (let [{:keys [chunk-id chunk-bytes chunk-stats]} (.readObject reader)
                chunk (chunk/chunk-from-bytes chunk-bytes)
                entry-stats (stats/->ChunkStats (:count chunk-stats)
                                                (:sum chunk-stats)
                                                (:sum-sq chunk-stats)
                                                (:min-val chunk-stats)
                                                (:max-val chunk-stats)
                                                (or (:null-count chunk-stats) 0))]
            (make-chunk-entry chunk-id chunk entry-stats))))

      ;; ChunkStats (defrecord from stratum.stats)
      "stratum.ChunkStats"
      (reify ReadHandler
        (read [_ reader _tag _component-count]
          (let [{:keys [count sum sum-sq min-val max-val null-count]} (.readObject reader)]
            (stats/->ChunkStats count sum sum-sq min-val max-val (or null-count 0)))))}

     :write-handlers
     {PersistentSortedSet
      {"stratum.PersistentSortedSet"
       (reify WriteHandler
         (write [_ writer pset]
           (when (nil? (.-_address ^PersistentSortedSet pset))
             (throw (ex-info "PSS must be stored before serialization" {:type :must-be-flushed})))
           (.writeTag writer "stratum.PersistentSortedSet" 1)
           (.writeObject writer {:meta (meta pset)
                                 :address (.-_address ^PersistentSortedSet pset)
                                 :count (count pset)})))}

      Leaf
      {"stratum.PersistentSortedSet.Leaf"
       (reify WriteHandler
         (write [_ writer leaf]
           (.writeTag writer "stratum.PersistentSortedSet.Leaf" 1)
           (.writeObject writer {:keys (vec (.keys ^Leaf leaf))})))}

      Branch
      {"stratum.PersistentSortedSet.Branch"
       (reify WriteHandler
         (write [_ writer node]
           (.writeTag writer "stratum.PersistentSortedSet.Branch" 1)
           (.writeObject writer {:level (.level ^Branch node)
                                 :keys (vec (.keys ^Branch node))
                                 :addresses (vec (.addresses ^Branch node))})))}}}))

(defn- chunk-entry-write-handler
  "Fressian write handler for ChunkEntry records.
   Serializes chunk data inline via chunk-to-bytes."
  []
  (reify WriteHandler
    (write [_ writer entry]
      (.writeTag writer "stratum.ChunkEntry" 1)
      (.writeObject writer {:chunk-id (:chunk-id entry)
                            :chunk-bytes (chunk/chunk-to-bytes (:chunk entry) (:stats entry))
                            :chunk-stats (let [s (:stats entry)]
                                           {:count (:count s)
                                            :sum (:sum s)
                                            :sum-sq (:sum-sq s)
                                            :min-val (:min-val s)
                                            :max-val (:max-val s)
                                            :null-count (:null-count s)})}))))

(defn- chunk-stats-write-handler
  "Fressian write handler for ChunkStats records."
  []
  (reify WriteHandler
    (write [_ writer stats]
      (.writeTag writer "stratum.ChunkStats" 1)
      (.writeObject writer {:count (:count stats)
                            :sum (:sum stats)
                            :sum-sq (:sum-sq stats)
                            :min-val (:min-val stats)
                            :max-val (:max-val stats)
                            :null-count (:null-count stats)}))))

;; ============================================================================
;; Factory Function
;; ============================================================================

(def ^:const DEFAULT_CACHE_SIZE
  "Default LRU node count for CachedStorage.

   The cache holds heterogeneous PSS nodes — small branches (a few hundred
   bytes) and fat leaves (up to BF=64 ChunkEntries × `chunk-size × 8` bytes
   each, which at the project default 8K rows is ~4MB per leaf). The LRU is
   count-bounded, so the practical byte ceiling = cache-size × max-leaf-size.

   PSS traversal at BF=64 needs only ~log_64(N) spine nodes plus the leaf
   under inspection — typically 4–5 nodes total even for billion-entry
   indices. 16 leaves headroom for a small working set without letting a
   single CachedStorage retain hundreds of MB of chunk data when nothing
   is querying it."
  16)

(defn create-storage
  "Create CachedStorage backed by a konserve store.

   Args:
     store - Konserve store (filestore, memory, etc.)

   Options:
     :cache-size   - LRU node count (default DEFAULT_CACHE_SIZE = 16).
     :crypto-hash? - Enable merkle tree addressing (default false)

   Returns: CachedStorage implementing IStorage."
  ([store] (create-storage store {}))
  ([store {:keys [cache-size crypto-hash?]
           :or {cache-size DEFAULT_CACHE_SIZE
                crypto-hash? false}}]
   (let [storage-atom (atom nil)
         handlers (create-fressian-handlers storage-atom)
         ;; Add ChunkEntry/ChunkStats write handlers (keyed by class, resolved lazily)
         chunk-entry-cls @chunk-entry-class
         all-write-handlers (assoc (:write-handlers handlers)
                                   chunk-entry-cls
                                   {"stratum.ChunkEntry" (chunk-entry-write-handler)}
                                   ChunkStats
                                   {"stratum.ChunkStats" (chunk-stats-write-handler)})
         config {:crypto-hash? crypto-hash? :cache-size cache-size}
         store (assoc store
                      :serializers {:FressianSerializer
                                    (fressian-serializer
                                     (:read-handlers handlers)
                                     all-write-handlers)})
         storage (->CachedStorage
                  store
                  config
                  (atom (cache/lru-cache-factory {} :threshold cache-size))
                  (atom {:writes 0 :reads 0 :accessed 0})
                  (atom []))]
     (reset! storage-atom storage)
     storage)))

;; ============================================================================
;; Utilities
;; ============================================================================

(def ^:const DEFAULT_FLUSH_PARALLELISM
  "Bound on in-flight `k/assoc` calls during a flush. Each in-flight write
   holds a Fressian byte-buffer of leaf data — an unbounded fan-out (e.g.
   firing all 92 leaf writes from a sync cycle simultaneously) inflates
   memory peak and overruns the OS page cache once dirty pages exceed
   `vm.dirty_ratio`, after which fsync queues serialize anyway. Bounded
   parallelism caps memory use and keeps konserve drainable at steady state."
  8)

(defn flush-writes-ch!
  "Drain pending writes via `core.async/pipeline-async`. Returns a channel
   that closes when all queued writes have completed. Uses bounded
   parallelism (default DEFAULT_FLUSH_PARALLELISM) so memory and OS-page-
   cache pressure stay bounded.

   Caller composes: `<!!` to block, or compose with other flushes."
  ([storage] (flush-writes-ch! storage DEFAULT_FLUSH_PARALLELISM))
  ([^CachedStorage storage parallelism]
   (let [store (.-store storage)
         pending @(.-pending-writes storage)
         done-ch (async/chan)]
     (if (empty? pending)
       (async/close! done-ch)
       (let [in-ch (async/to-chan! pending)
             out-ch (async/chan parallelism)
             af (fn [[address node] result-ch]
                  (let [w-ch (k/assoc store address node {:sync? false})]
                    (async/take! w-ch (fn [_] (async/close! result-ch)))))]
         (async/pipeline-async parallelism out-ch af in-ch)
         (async/go
           (loop [] (when (async/<! out-ch) (recur)))
           (swap! (.-pending-writes storage)
                  (fn [cur] (vec (drop (count pending) cur))))
           (async/close! done-ch))))
     done-ch)))

(defn flush-writes!
  "Blocking flush. See `flush-writes-ch!` for the channel-returning variant."
  [^CachedStorage storage]
  (async/<!! (flush-writes-ch! storage)))

(defn flush-storages-ch!
  "Drain pending writes from a *collection* of CachedStorages in a single
   bounded-parallel fan-out. All storages share one in-flight budget so
   total memory pressure stays bounded regardless of column count.

   Returns a channel that closes when all writes from all storages
   complete. Pending-writes atoms are atomically drained in proportion."
  ([storages] (flush-storages-ch! storages DEFAULT_FLUSH_PARALLELISM))
  ([storages parallelism]
   (let [;; Snapshot each storage's pending list — note: not yet drained.
         per-storage (mapv (fn [^CachedStorage s]
                             [s @(.-pending-writes s)])
                           storages)
         all-items (mapcat (fn [[s pending]]
                             (map (fn [[a n]] [s a n]) pending))
                           per-storage)
         done-ch (async/chan)]
     (if (empty? all-items)
       (async/close! done-ch)
       (let [in-ch (async/to-chan! all-items)
             out-ch (async/chan parallelism)
             af (fn [[^CachedStorage storage address node] result-ch]
                  (let [w-ch (k/assoc (.-store storage) address node
                                      {:sync? false})]
                    (async/take! w-ch (fn [_] (async/close! result-ch)))))]
         (async/pipeline-async parallelism out-ch af in-ch)
         (async/go
           (loop [] (when (async/<! out-ch) (recur)))
           ;; Atomically drop processed items from each storage.
           (doseq [[^CachedStorage s pending] per-storage
                   :let [n (count pending)]
                   :when (pos? n)]
             (swap! (.-pending-writes s)
                    (fn [cur] (vec (drop n cur)))))
           (async/close! done-ch))))
     done-ch)))

(defn storage-stats
  "Get storage statistics: {:writes N :reads N :accessed N}."
  [^CachedStorage storage]
  @(.-stats storage))

(defn pending-write-count
  "Return number of pending writes waiting to be flushed."
  [^CachedStorage storage]
  (count @(.-pending-writes storage)))

(defn clear-cache!
  "Clear the LRU cache. Nodes will be re-loaded from storage on next
   access. Preserves the cache-size from the storage's original config."
  [^CachedStorage storage]
  (let [size (or (:cache-size (.-config storage)) DEFAULT_CACHE_SIZE)]
    (reset! (.-cache storage) (cache/lru-cache-factory {} :threshold size)))
  nil)

(defn cache-size
  "Return number of nodes currently in cache."
  [^CachedStorage storage]
  (count @(.-cache storage)))
